### ISSUE TITLE
Adição de .gittgnore :D

### ISSUE THREAD

**Issue by dhelbegor** [GomesMilla/Controle-de-estoque#1]
Logo mais poderia ver a possibilidade de adicionar um .gitignore, assim tu evita de versionar coisas como compilados `__pycache__` e o seu proprio banco de dados no caso db.sqlite3. a não ser que esse seja o propósito :D

[o que é .gitignore?](https://womakerscode.gitbook.io/desvendando-git-e-github/ciclo-de-vida-basico/o-que-e-o-.gitignore)

exemplo prático:
crie um arquivo de nome `.gitignore` na pasta raiz no projeto, no mesmo nivel do `manage.py` e adicione os seguintes items.
```
__pycache__/
bin/
include/
lib/
.venv/

*~
*.sqlite3
*.db
*.pyc
```

exemplo de arquivos os quais não precisamos/devemos versionar, isso vale também para arquivos de variaveis de ambiente como .env que geralmente contém credenciais de acessos.

Happy coding :D

**Comment by GomesMilla** [comment]
Obrigada pela dica, confesso que quando fiz, não sabia usar, aí subia tudo.Hoje eu sei usar, aprendi essa semana
________________________________
De: Adailton Nascimento ***@***.***>
Enviado: segunda-feira, 28 de junho de 2021 12:30
Para: GomesMilla/Controle-de-estoque ***@***.***>
Cc: Subscribed ***@***.***>
Assunto: [GomesMilla/Controle-de-estoque] Adição de .gittgnore :D (#1)


Logo mais poderia ver a possibilidade de adicionar um .gitignore, assim tu evita de versionar coisas como compilados __pycache__ e o seu proprio banco de dados no caso db.sqlite3. a não ser que esse seja o propósito :D

o que é .gitignore?<https://womakerscode.gitbook.io/desvendando-git-e-github/ciclo-de-vida-basico/o-que-e-o-.gitignore>

exemplo prático:
crie um arquivo de nome .gitignore na pasta raiz no projeto, no mesmo nivel do manage.py e adicione os seguintes items.

__pycache__/

bin/

include/

lib/

.venv/



*~

*.sqlite3

*.db

*.pyc



exemplo de arquivos os quais não precisamos/devemos versionar, isso vale também para arquivos de variaveis de ambiente como .env que geralmente contém credenciais de acessos.

Happy coding :D
